export default function stringTranslate(string) {
    const languages = {
        'pt-br': {
            'title': "Título",
            'name_alternative': "Nome Alternativo",
            'features': "Caracteristicas",
            'excerpt': "Resumo",
            'thumbnail': "Imagem",
            'user_id': 'Autor',
            'created_at': 'Criação',
            'updated_at': 'Atualização',
            'menu_id': 'Menu',
            'brand': 'Marca',
            'name': 'Nome',
            'description': 'Descrição',
            'subject': 'Assunto',
            'message': 'Mensagem',
            'author': 'Autor',
            'testimony': 'Depoimento',
            'avatar': 'Imagem',
            'active': 'Ativo',
            'year': 'Ano',
            'image': 'Imagem',
            'first_name': 'Primeiro Nome',
            'last_name': 'Sobrenome',
            'document': 'CPF/CNPJ',
            'email': 'E-mail',
            'birthday': 'Data de Nascimento',
            'phone': 'Telefone',
            'genre': 'Sexo',
            'postal_code': 'CEP',
            'number': 'Número',
            'city': 'Cidade',
            'district': 'Bairro',
            'state': 'Estado',
            'complement': 'Complemento',
            'obs': 'Observações',
            'partners': 'Parceiros',
            'posts': 'Notícias',
            'categories': 'Categorias',
            'pages': 'Páginas',
            'numbers': 'Números',
            'icon': 'Ícone',
            'programs': 'Programas',
            'projects': 'Projetos',
            'contacts': 'Contatos',
            'testimonials': 'Depoimentos',
            'reports': 'Transparência',
            'registries': 'Cadastros',
            'awards': 'Prêmios',
            'speeches': 'Palavras da Presidente',
            'users': 'Usuários',
            'settings': 'Configurações',
            'facebook_user': 'Facebook',
            'instagram_user': 'Instagram',
            'twitter_user': 'Twitter',
            'linkedin_user': 'Linkedin',
            'youtube_user': 'Youtube',
            'whatsapp_number': 'WhatsApp',
            'phone_number': 'Telefone',
            'address': 'Endereço',
            'email_notification_contact': 'E-mail Contatos',
            'email_notification_signup': 'E-mail Geral',
            'email_notification_job': 'E-mail Trabalhe conosco',
            'email_notification_complaint': 'E-mail Canal de Denúncia',
            'email_notification_testimonial': 'E-mail Depoimentos',
            'email_notification_partner': 'E-mail Parceiros',
            'email_notification_partner': 'E-mail Doações',
            'email_notification_project': 'E-mail Projetos',
            'email_notification_volunteer': 'E-mail Voluntários',
            'video_index': 'Vídeo da Página Inicial',
            'path': 'Link Interno',
            'thumbnail': 'Miniatura',
            'program_id': 'Programa',
            'category': 'Categorias',
            'file': 'Arquivo',
            'speech': 'Discurso',
            'menus': 'Menus',
            'submenus': 'Submenus',
            'id': '#',
            'category_id': 'Categoria',
            'partnercategories': 'Categoria dos Parceiros',
            'page': 'Página',
            'headers': 'Cabeçalhos',
            'donation': 'Caixas de Doação',
            'feature': 'Na Página Inicial?',
            'internal': 'Exibe ao clicar',
            'button_text': 'Texto do Botão',
            'order': 'Ordem',
            'terms': 'Aceitou os termos?',
            'new': 'Novo',
            'picture': 'Imagens',
            'base_materials': 'Materiais Base',
            'pictures': 'Imagem',
            'base_material_id': 'Nome',
            'identification_number': 'Identificação',
            'local_id': 'Local',
            'sublocal_id': 'Sublocal',
            'conservation': 'N. de Conservação',
            'usability': 'N. de Usabilidade',
            'unit_id': 'Unidade',
            'materials': 'Materiais',
            'locals': 'Locais',
            'sublocals': 'Sublocais',
            'loans': 'Cautelas',
            'registry': 'Matrícula',
            'role': 'Função',
            'price': 'Preço',
            'management': 'Gestão',
            'histories': 'Histórico'
        }
    }

    const newString = languages[process.env.NEXT_PUBLIC_LANGUAGE][string]

    if (newString) {
        return newString
    }
    return string
}